[project]
name = "hello"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "termcolor==1.1.0",
    "opentitanlib",
]

[project.scripts]
hello = "hello:main"
bye = "hello:bye"