// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

`include "otbn_base_vseq.sv"
`include "otbn_common_vseq.sv"
`include "otbn_multi_vseq.sv"
`include "otbn_reset_vseq.sv"
`include "otbn_sequential_vseq.sv"
`include "otbn_single_vseq.sv"
`include "otbn_smoke_vseq.sv"
`include "otbn_imem_err_vseq.sv"
`include "otbn_dmem_err_vseq.sv"
`include "otbn_stress_all_vseq.sv"
`include "otbn_escalate_vseq.sv"
`include "otbn_zero_state_err_urnd_vseq.sv"
`include "otbn_illegal_mem_acc_vseq.sv"
`include "otbn_sw_errs_fatal_chk_vseq.sv"
`include "otbn_intg_err_vseq.sv"
`include "otbn_alu_bignum_mod_err_vseq.sv"
`include "otbn_controller_ispr_rdata_err_vseq.sv"
`include "otbn_mac_bignum_acc_err_vseq.sv"
`include "otbn_pc_ctrl_flow_redun_vseq.sv"
`include "otbn_rnd_sec_cm_vseq.sv"
`include "otbn_ctrl_redun_vseq.sv"
`include "otbn_sec_wipe_err_vseq.sv"
`include "otbn_urnd_err_vseq.sv"
