# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Updates are scheduled at the beginning of the work week.
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[dependabot]"
    # Ignore packages fetched from GitHub URLs.
    ignore:
      - dependency-name: "*fusesoc*"
      - dependency-name: "*edalize*"
      - dependency-name: "*chipwhisperer*"
    reviewers:
      - "lowRISC/ot-python-reviewers"

  - package-ecosystem: "cargo"
    directory: "/third_party/rust"
    schedule:
      # Updates are scheduled at the beginning of the work week.
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[dependabot]"
    reviewers:
      - "lowRISC/ot-rust-reviewers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Updates are scheduled at the beginning of the work week.
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "[dependabot]"
