# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "rom_ext_real_prod_signed_slot_a",
    srcs = ["rom_ext_real_prod_signed_slot_a_silicon_creator.signed.bin"],
)

filegroup(
    name = "rom_ext_real_prod_signed_slot_b",
    srcs = ["rom_ext_real_prod_signed_slot_b_silicon_creator.signed.bin"],
)
