// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// alert_handler_env_pkg__params.sv is auto-generated by `topgen.py` tool

parameter string LIST_OF_ALERTS[] = {
  "aes_ctrl_err_update",
  "aes_ctrl_err_storage",
  "hmac_msg_push_sha_disabled",
  "otbn_imem_uncorrectable",
  "otbn_dmem_uncorrectable",
  "otbn_reg_uncorrectable",
  "sensor_ctrl_ast_alerts",
  "keymgr_err"
};

parameter uint NUM_ALERTS = 8;
