[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "src"
title = "Getting Started"

[output.html]
git-repository-url = "https://github.com/lowrisc/opentitan"
edit-url-template = "https://github.com/lowrisc/opentitan/edit/master/doc/guides/getting_started/{path}"
curly-quotes = true

[preprocessor.toolversion]
command = "../../../util/mdbook-toolversion"

