# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "mldsa87_ntt",
    srcs = [
        "mldsa87_ntt.s",
    ],
)

otbn_library(
    name = "mldsa87_arith",
    srcs = [
        "mldsa87_arith.s",
    ],
)

otbn_library(
    name = "mldsa87_xof",
    srcs = [
        "mldsa87_xof.s",
    ],
)

otbn_library(
    name = "mldsa87_rounding",
    srcs = [
        "mldsa87_rounding.s",
    ],
)

otbn_library(
    name = "mldsa87_norm",
    srcs = [
        "mldsa87_norm.s",
    ],
)

otbn_library(
    name = "mldsa87_sample",
    srcs = [
        "mldsa87_sample.s",
    ],
)

otbn_library(
    name = "mldsa87_expand",
    srcs = [
        "mldsa87_expand.s",
    ],
)

otbn_library(
    name = "mldsa87_utils",
    srcs = [
        "mldsa87_utils.s",
    ],
)
