# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "doc_files",
    srcs = glob(["**/*.md"]) + [
        "//sw/host/hsmtool:doc_files",
        "//sw/host/opentitanlib:doc_files",
        "//sw/host/opentitansession:doc_files",
        "//sw/host/opentitantool:doc_files",
        "//sw/host/ot_certs:doc_files",
        "//sw/host/tpm2_test_server:doc_files",
    ],
)
