// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Base class for alert and escalation transactions

class alert_esc_seq_item extends uvm_sequence_item;
  // If this field is nonzero, the driver will cause a signal integrity error of that many cycles
  // when driving this item.
  rand int unsigned m_int_err_cyc;

  // This bit is set on items generated by a monitor that has seen a timeout caused by an
  // alert/escalation sender not responding to a ping.
  //
  // The field is also used in sequence items that are randomised and will be driven. For example,
  // see esc_receiver_base_seq.
  rand bit m_ping_timeout;

  // This value is only set by monitors and gives the type of the transaction that has been seen (a
  // ping, an alert/escalation, or a signal integrity failure).
  alert_esc_trans_type_e m_trans_type;

  // Constraint on possible values for m_int_err_cyc
  //
  // This has a soft constraint that asks m_int_err_cyc is zero, meaning no integrity error. That
  // constraint can be overridden when randomising the item. The constraint also controls the number
  // of cycles an error will last: either 1 or a random value between 2 and 10.
  extern constraint int_err_cyc_c;

  `uvm_object_utils_begin(alert_esc_seq_item)
    `uvm_field_int (m_int_err_cyc,  UVM_DEFAULT)
    `uvm_field_int (m_ping_timeout, UVM_DEFAULT)

    `uvm_field_enum(alert_esc_trans_type_e, m_trans_type, UVM_DEFAULT)
  `uvm_object_utils_end

  extern function new (string name = "");
endclass : alert_esc_seq_item

constraint alert_esc_seq_item::int_err_cyc_c {
  // Normally we constrain m_int_err_cyc to be zero. But it's a soft constraint, so the call-site
  // that drives the randomisation can override it by adding a hard "m_int_err_cyc != 0" constraint.
  //
  // If the call-site *has* overridden the constraint (but hasn't disabled this whole constraint by
  // name), we want to control the distribution of values. The obvious way to express that would be
  // something like "m_int_err_cyc != 0 -> m_int_err_cyc dist {some_distribution_here};", but that
  // doesn't work EDA tools that can't solve distributions in parallel with hard constraints.
  //
  // Fortunately, we can cheat! The trick is to use a single distribution statement that gives a
  // nonzero probability to m_int_err_cyc == 0. This allows the usual case (where the value is
  // *constrained* to equal zero), and doesn't affect the special case (because the value is already
  // constrained not to equal zero).
  soft m_int_err_cyc == 0;
  m_int_err_cyc dist {0 := 1, 1 :/ 1, [2:10] :/ 1};
}

function alert_esc_seq_item::new (string name = "");
  super.new(name);
endfunction : new
