# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules/opentitan:cc.bzl", "exec_env_filegroup")

package(default_visibility = ["//visibility:public"])

exec_env_filegroup(
    name = "ft_personalize_sival",
    testonly = True,
    exec_env = {
    },
    files = {
    },
)
