# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# This configuration file enables ALL Ruff lints. Enable it with:
#
# ```
# ruff check --config ci/lint/ruff.toml
# ```
#
# Currently most files are excluded because they currently fail. If you would like a file
# to be clean for ALL lints, remove it from the list below.
#
# Note: this configuration file should not be in a directory containing any Python,
# otherwise it will apply to those files even when `--config` is not used.

target-version = "py310"
line-length = 100
extend-exclude = [
  # Don't lint vendored files which must be fixed upstream.
  "*vendor*",
  # Files and directories that currently fail linting. Anyone is welcome to resolve issues
  # in these files and remove them from the list. Please do not add to it unless necessary.
  "ci/scripts/**/*.py",
  "hw/check_tool_requirements.py",
  "hw/dv/tools/ralgen/ralgen.py",
  "hw/formal/tools/csr_assert_gen/*.py",
  "hw/formal/tools/jaspergold/*.py",
  "hw/formal/tools/vcformal/*.py",
  "hw/ip/aes/pre_dv/aes_sbox_lec/*.py",
  "hw/ip/aes/pre_sca/alma_post_syn/*.py",
  "hw/*/ip_autogen/pwrmgr/util/reg_pwrmgr.py",
  "hw/ip/hmac/model/hmac_model.py",
  "hw/ip/otbn/dv/otbnsim/**/*.py",
  "hw/ip/otbn/dv/rig/rig/**.py",
  "hw/ip/otbn/dv/uvm/gen-binaries.py",
  "hw/ip/otbn/dv/verilator/run-some.py",
  "hw/ip/otbn/util/**.py",
  "hw/ip/prim/pre_dv/prim_crc32/expected_out.py",
  "hw/ip/prim/util/**.py",
  "hw/ip/rom_ctrl/util/*.py",
  "hw/ip/rv_timer/util/*.py",
  "hw/ip_templates/pwrmgr/util/reg_pwrmgr.py",
  "hw/syn/tools/dc/*.py",
  "hw/tool_requirements.py",
  "hw/top_englishbreakfast/util/prepare_sw.py",
  "rules/scripts/bitstreams_workspace*.py",
  "rules/scripts/clang_tidy.py",
  "sw/device/examples/teacup_demos/data/c-array-bitmap-generator.py",
  "sw/device/silicon_creator/lib/sigverify/**/*.py",
  "sw/device/tests/crypto/*.py",
  "sw/device/tests/crypto/testvectors/**/*.py",
  "sw/device/tests/otbn_data/otbn_test_params.py",
  "sw/host/cryptotest/testvectors/parsers/*.py",
  "sw/host/hsmtool/scripts/pkcs11_consts.py",
  "sw/host/tests/manuf/manuf_cp_device_info_flash_wr/gen_test_exit_token.py",
  "sw/host/tests/manuf/manuf_cp_test_lock/gen_test_unlock_token.py",
  "sw/host/tests/rom/e2e_bootstrap_rma/gen_rma_token.py",
  "sw/otbn/crypto/tests/generated/*.py",
  "util/autogen_banner.py",
  "util/autogen_dif.py",
  "util/autogen_testutils/*.py",
  "util/cmdgen.py",
  "util/coverage/*.py",
  "util/dashboard/*.py",
  "util/design/**/*.py",
  "util/device_sw_utils/*.py",
  "util/diff_generated_util_output.py",
  "util/dtgen/*.py",
  "util/dttool.py",
  "util/dvsim/*.py",
  "util/fix_include_guard.py",
  "util/fix_trailing_whitespace.py",
  "util/fpga/*.py",
  "util/fpvgen.py",
  "util/fpvgen/*.py",
  "util/fusesoc_build.py",
  "util/gen_doc_hw_summary_table.py",
  "util/generate_compilation_db*.py",
  "util/gen_testutils.py",
  "util/get-toolchain.py",
  "util/i2csvg.py",
  "util/i2csvg/*.py",
  "util/ipgen.py",
  "util/ipgen/**/*.py",
  "util/lint_commits.py",
  "util/lintpy.py",
  "util/make_new_dif.py",
  "util/make_new_dif/*.py",
  "util/mdbook/*.py",
  "util/mdbook_*.py",
  "util/otbn_build.py",
  "util/py/**/*.py",
  "util/raclgen.py",
  "util/raclgen/*.py",
  "util/reggen/*.py",
  "util/regtool.py",
  "util/repo_top.py",
  "util/rom_chip_info*.py",
  "util/run_manual_tests.py",
  "util/selfdoc.py",
  "util/serialize/*.py",
  "util/site/*.py",
  "util/test_reggen/*.py",
  "util/tlgen.py",
  "util/tlgen/*.py",
  "util/topgen.py",
  "util/topgen/*.py",
  "util/uvmdvgen.py",
  "util/uvmdvgen/*.py",
  "util/validate_testplans.py",
  "util/vendor.py",
  "util/verible-format.py",
  "util/version_file.py",
]

[lint]
preview = true
explicit-preview-rules = true
select = ["ALL", "E303", "W391"]
# Ignore conflicting rules as recommended
ignore = ["D203", "D213", "COM812", "ISC001"]
