# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Install dependencies
description: Install system dependencies needed for OpenTitan

inputs:
  verilator-version:
    description: Verilator version to install
    required: true
    default: '4.210'
  verilator-path:
    description: Path at which to install Veriltator
    required: true
    default: /tools/verilator
  verible-version:
    description: Verible version to install
    required: true
    default: 'v0.0-3622-g07b310a3'
  verible-path:
    description: Path at which to install Verible
    required: true
    default: /tools/verible

runs:
  using: composite
  steps:
    - name: Install system dependencies
      run: |
        sudo apt update
        grep '^[^#]' apt-requirements.txt | xargs sudo apt install -y
      shell: bash

    - uses: astral-sh/setup-uv@v3
      with:
        version: '0.4.20'
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
          python-requirements.txt

    - name: Install Python
      shell: bash
      run: |
        uv python install 3.8
        # Create a virtual environment for UV
        uv venv ~/.local/share/venv
        echo "$HOME/.local/share/venv/bin" >> "$GITHUB_PATH"
        echo "VIRTUAL_ENV=$HOME/.local/share/venv" >> "$GITHUB_ENV"

    - name: Install Python dependencies
      shell: bash
      run: |
        uv pip install -r python-requirements.txt --require-hashes
        # We installed uv from setup-uv action, so uninstall from venv to prevent conflict
        uv pip uninstall uv

    - name: Install Verilator
      run: |
        VERILATOR_TAR="verilator-v${{ inputs.verilator-version }}.tar.gz"
        VERILATOR_URL="https://storage.googleapis.com/verilator-builds/${VERILATOR_TAR}"
        curl -f -Ls -o "/tmp/${VERILATOR_TAR}" "$VERILATOR_URL" || {
          echo "failed to download Verilator from ${VERILATOR_URL}" >&2
          exit 1
        }
        sudo mkdir -p "${{ inputs.verilator-path }}"
        sudo chmod 777 "${{ inputs.verilator-path }}"
        tar -C "${{ inputs.verilator-path }}" -xvzf "/tmp/${VERILATOR_TAR}"
        echo "${{ inputs.verilator-path }}/v${{ inputs.verilator-version }}/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Install Verible
      run: |
        VERIBLE_TAR="verible-${{ inputs.verible-version }}-linux-static-x86_64.tar.gz"
        VERIBLE_URL="https://github.com/chipsalliance/verible/releases/download/${{ inputs.verible-version }}/${VERIBLE_TAR}"
        curl -f -Ls -o "/tmp/${VERIBLE_TAR}" "$VERIBLE_URL" || {
          echo "failed to download Verible from ${VERIBLE_URL}" >&2
          exit 1
        }
        sudo mkdir -p "${{ inputs.verible-path }}"
        sudo chmod 777 "${{ inputs.verible-path }}"
        tar -C "${{ inputs.verible-path }}" -xvzf "/tmp/${VERIBLE_TAR}" --strip-components=1
        echo "${{ inputs.verible-path }}/bin" >> "$GITHUB_PATH"
      shell: bash
