# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

cc_import(
    name = "nop_imm_rom_ext",
    objects = ["nop.o"],
    alwayslink = 1,
)
