# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

worker_processes  1;
daemon on;
pid nginx.pid;
error_log stderr crit;

events {
    worker_connections  1024;
}

http {
    keepalive_timeout  120s 120s;
    keepalive_requests 1024;

    # Map request details to our custom HIT/MISS tags
    map "$request_method:$status:$upstream_status" $log_tag {
        "~^PUT:2.."                         "PUT";  # Successful PUT
        "~^(GET|HEAD):2..:(.*,\s*)?2..$"    "DOWN"; # Upstream HIT
        "~^(GET|HEAD):2..:$"                "HIT";  # Local HIT
        "~^(GET|HEAD):404:(.*,\s*)?4..$"    "MISS"; # Upstream MISS
        default "UNK:$request_method:$status:$upstream_status";
    }

    log_format custom '$log_tag\tdata$uri';

    access_log access.log custom;

    # Define temporary paths within the project directory to avoid permission issues
    client_body_temp_path data/tmp;
    proxy_temp_path       data/tmp;

    server {
        listen       8388;
        server_name  127.0.0.1;

        # The path to the directory where nginx should store the cache contents.
        root data;
        client_max_body_size 1G;

        location / {
            # 1. Handle PUT separately to ensure DAV is used and not try_files.
            if ($request_method = PUT) {
                error_page 418 = @dav;
                return 418;
            }

            # 2. For GET/HEAD, try local file first.
            try_files $uri @proxy_upstream;
        }

        # Named location for DAV PUT operations
        location @dav {
            dav_methods PUT;
            dav_access user:rw group:rw all:rw;
            create_full_put_path on;
            allow all;
        }

        # Named location for proxying to GCS
        location @proxy_upstream {
            if ($request_method !~ ^(GET|HEAD)$ ) {
                return 404;
            }
            proxy_set_header Host storage.googleapis.com;
            proxy_ssl_server_name on;
            proxy_pass https://gcs-backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }

    upstream gcs-backend {
        server storage.googleapis.com:443;
        keepalive 1024;
    }
}
