# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

cc_library(
    name = "bfv_decoder",
    srcs = ["bfv_decoder.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//sw/device/silicon_creator/lib:error",
    ],
)
