# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "rtl_files",
    srcs = glob(
        ["**"],
    ) + [
        "//hw/top_englishbreakfast/ip_autogen/clkmgr:rtl_files",
        "//hw/top_englishbreakfast/ip_autogen/flash_ctrl:rtl_files",
        "//hw/top_englishbreakfast/ip_autogen/pinmux:rtl_files",
        "//hw/top_englishbreakfast/ip_autogen/pwrmgr:rtl_files",
        "//hw/top_englishbreakfast/ip_autogen/rstmgr:rtl_files",
        "//hw/top_englishbreakfast/ip_autogen/rv_plic:rtl_files",
    ],
    visibility = ["//visibility:public"],
)
