# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Darjeeling
description: Issues specific to top_darjeeling.
title: "[top_darjeeling] "
labels: ["Component:Darjeeling"]
body:
  - type: textarea
    id: desc
    attributes:
      label: desc
      value: |
        Please describe issue or task
