# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["**"]) + [
        "//hw/top_darjeeling/ip/ast:all_files",
        "//hw/top_darjeeling/ip/clkmgr:all_files",
        "//hw/top_darjeeling/ip/flash_ctrl:all_files",
        "//hw/top_darjeeling/ip/pinmux:all_files",
        "//hw/top_darjeeling/ip/pwrmgr:all_files",
        "//hw/top_darjeeling/ip/rstmgr:all_files",
        "//hw/top_darjeeling/ip/sensor_ctrl:all_files",
        "//hw/top_darjeeling/ip/soc_proxy:all_files",
        "//hw/top_darjeeling/ip/xbar:all_files",
        "//hw/top_darjeeling/ip/xbar_main:all_files",
        "//hw/top_darjeeling/ip/xbar_peri:all_files",
    ],
)
