# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["**"]) + [
        "//hw/ip/adc_ctrl:all_files",
        "//hw/ip/aes:all_files",
        "//hw/ip/aon_timer:all_files",
        "//hw/ip/clkmgr:all_files",
        "//hw/ip/csrng:all_files",
        "//hw/ip/edn:all_files",
        "//hw/ip/entropy_src:all_files",
        "//hw/ip/flash_ctrl:all_files",
        "//hw/ip/gpio:all_files",
        "//hw/ip/hmac:all_files",
        "//hw/ip/i2c:all_files",
        "//hw/ip/keymgr:all_files",
        "//hw/ip/kmac:all_files",
        "//hw/ip/lc_ctrl:all_files",
        "//hw/ip/otbn:all_files",
        "//hw/ip/otp_ctrl:all_files",
        "//hw/ip/pattgen:all_files",
        "//hw/ip/pinmux:all_files",
        "//hw/ip/prim:all_files",
        "//hw/ip/prim_generic:all_files",
        "//hw/ip/prim_xilinx:all_files",
        "//hw/ip/prim_xilinx_ultrascale:all_files",
        "//hw/ip/pwm:all_files",
        "//hw/ip/pwrmgr:all_files",
        "//hw/ip/rom_ctrl:all_files",
        "//hw/ip/rstmgr:all_files",
        "//hw/ip/rv_core_ibex:all_files",
        "//hw/ip/rv_dm:all_files",
        "//hw/ip/rv_timer:all_files",
        "//hw/ip/spi_device:all_files",
        "//hw/ip/spi_host:all_files",
        "//hw/ip/sram_ctrl:all_files",
        "//hw/ip/sysrst_ctrl:all_files",
        "//hw/ip/tlul:all_files",
        "//hw/ip/trial1:all_files",
        "//hw/ip/uart:all_files",
        "//hw/ip/usbdev:all_files",
    ],
)
