# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "opentitan"
version = "0.1.0"
authors = ["lowRISC contributors"]
build = "build.rs"
edition = "2018"

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[features]
fpga_nexysvideo = ["earlgrey/fpga_nexysvideo"]
sim_verilator = ["earlgrey/sim_verilator"]

[dependencies]
earlgrey = { path = "../../chips/earlgrey" }
tock = { path = "../../tock" }
