[package]
name = "opentitan"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[dependencies]
components = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
rv32i = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
capsules = { git = "https://github.com/tock/tock", rev = "d37ef3d2"}
kernel = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
earlgrey = { path = "../../chips/earlgrey" }
