[package]
name = "opentitan"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"

[profile.dev]
panic = "abort"
lto = false
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[features]
device_fpga = ["earlgrey/device_fpga"]
device_verilator = ["earlgrey/device_verilator"]

[dependencies]
earlgrey = { path = "../../chips/earlgrey" }
tock_deps = { path = "../../tock_deps" }
