# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "rsa_signatures",
    srcs = glob(["*.rsa.sig"]),
)

filegroup(
    name = "spx_signatures",
    srcs = glob(["*.spx.sig"]),
)
