#!/usr/bin/env bash
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
set -e

source "$(dirname "$0")/common.sh"
verible_wrapper_run verible-verilog-syntax "$@"
