# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# List of IPs for which to generate headers.
OPENTITAN_ALL_IPS = [
    "adc_ctrl",
    "aes",
    "alert_handler",
    "aon_timer",
    "ast",
    "clkmgr",
    "csrng",
    "dma",
    "edn",
    "entropy_src",
    "flash_ctrl",
    "gpio",
    "hmac",
    "i2c",
    "keymgr",
    "keymgr_dpe",
    "kmac",
    "lc_ctrl",
    "mbx",
    "otbn",
    "otp_ctrl",
    "pattgen",
    "pinmux",
    "pwm",
    "pwrmgr",
    "rom_ctrl",
    "rstmgr",
    "rv_core_ibex",
    "rv_dm",
    "rv_plic",
    "rv_timer",
    "sensor_ctrl",
    "spi_device",
    "spi_host",
    "sram_ctrl",
    "sysrst_ctrl",
    "uart",
    "usbdev",
]
