// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//==================================================
// This file contains the Excluded objects
// Generated By User: udij
// Format Version: 2
// Date: Wed Jul  7 16:56:32 2021
// ExclMode: default
//==================================================
CHECKSUM: "2224922822 3814218557"
INSTANCE: tb.dut.u_app_intf
ANNOTATION: "[UNSUPPORTED] nothing uses SHA3 application interface as of right now"
Branch 11 "4188171746" "(!rst_ni)" (5) "(!rst_ni) 0,0,1,-,0,-"
ANNOTATION: "[UNSUPPORTED] nothing uses SHA3 application interface as of right now"
Branch 11 "4188171746" "(!rst_ni)" (4) "(!rst_ni) 0,0,1,-,1,-"
