# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files([
    "hmac_sha256_expected.json",
    "hmac_sha256_vectors.json",
    "cshake_expected.json",
    "cshake_vectors.json",
    "rsa_expected.json",
    "rsa_vectors.json",
])
