# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files([
    "cshake_expected.json",
    "cshake_vectors.json",
    "eddsa_expected.hjson",
    "eddsa_vectors.hjson",
    "hmac_sha256_expected.json",
    "hmac_sha256_vectors.json",
    "rsa_expected.json",
    "rsa_vectors.json",
    "x25519_vectors.hjson",
])
