#!/bin/bash

# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Script to run connectivity test using Jasper Gold
#
# Usage: To run connectivity test on module top_earlgrey_asic, type
#   formal_conn
#
# More options:
# -p:  provide core file path
# -gui: run with GUI
# -cov: run coverage
# -t: choose which formal tool to use, current only support jaspergold
#
# Example:
#   formal_conn -gui -cov
#

export FPV_TOP=top_earlgrey_asic
gui=0
tool="jg"
export COV=0

while [ "$1" != "" ]; do
  case "$1" in
    "-top")
      shift
      FPV_TOP=$1
      ;;
    "-p")
      shift
      CORE_PATH=$1
      ;;
    "-gui")
      gui=1
      echo "using jasper gold GUI"
      ;;
    "-cov")
      COV=1
      echo "enable FPV coverage"
      ;;
    "-t")
      shift
      tool=$1
      echo "running in tool: $tool"
      ;;
  esac
  shift
done

echo "-------------------------------------------------------------------------"
echo "-- Generate file list using FuseSoC"
echo "-------------------------------------------------------------------------"
echo ""
echo "Top: $FPV_TOP"
echo ""

\rm -Rf build jgproject
# we just run the setup for the default target in order to generate the filelist
if [ "${CORE_PATH}" == "" ]; then
  CORE_PATH=systems:top_earlgrey_asic
fi
echo "core_file path: lowrisc:${CORE_PATH}"

fusesoc --cores-root ../.. run --tool=icarus --target=default --setup "lowrisc:${CORE_PATH}"

echo "-------------------------------------------------------------------------"
echo "-- Run JasperGold"
echo "-------------------------------------------------------------------------"

cd build/*${FPV_TOP}*/default-icarus

if [ "${tool}" == "jg" ]; then
  if [ "${gui}" == "1" ]; then
    jg ../../../jg_conn.tcl \
       -proj ../../../jgproject \
       -allow_unsupported_OS \
       | tee ../../../jg_conn.log
  else
    jg -batch \
      ../../../jg_conn.tcl \
      -proj ../../../jgproject \
      -allow_unsupported_OS \
      -command exit \
      | tee ../../../jg_conn.log
  fi
else
 echo "-- ERROR: TOOL ${tool} not supported"
fi
cd -

echo "-------------------------------------------------------------------------"
echo "-- Done"
echo "-------------------------------------------------------------------------"
