load("@io_bazel_stardoc//stardoc:stardoc.bzl", "stardoc")

stardoc(
    name = "gcc_arm_none_compiler_docs",
    out = "gcc_arm_none_compiler.md",
    input = "gcc_arm_none_repository.bzl",
    symbol_names = ["gcc_arm_none_compiler"],
)
