# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "unauthorized_private_key_0",
    srcs = ["unauthorized_0_rsa_3072_exp_f4.der"],
)
