# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:opentitan.bzl", "OPENTITAN_CPU")

package(default_visibility = ["//visibility:public"])

# This is a convenience alias so that software can import devicetables
# without having to know how it is wired to the top.
alias(
    name = "devicetables",
    actual = "//hw/top:devicetables",
)
