# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "fi_crypto",
    srcs = ["fi_crypto.json"],
)

filegroup(
    name = "fi_ibex",
    srcs = ["fi_ibex.json"],
)

filegroup(
    name = "fi_lc_ctrl",
    srcs = ["fi_lc_ctrl.json"],
)

filegroup(
    name = "fi_otbn",
    srcs = ["fi_otbn.json"],
)

filegroup(
    name = "fi_otp",
    srcs = ["fi_otp.json"],
)

filegroup(
    name = "fi_rng",
    srcs = ["fi_rng.json"],
)

filegroup(
    name = "fi_rom",
    srcs = ["fi_rom.json"],
)

filegroup(
    name = "sca_aes",
    srcs = ["sca_aes.json"],
)

filegroup(
    name = "sca_edn",
    srcs = ["sca_edn.json"],
)

filegroup(
    name = "sca_hmac",
    srcs = ["sca_hmac.json"],
)

filegroup(
    name = "sca_ibex",
    srcs = ["sca_ibex.json"],
)

filegroup(
    name = "sca_kmac",
    srcs = ["sca_kmac.json"],
)

filegroup(
    name = "sca_otbn",
    srcs = ["sca_otbn.json"],
)

filegroup(
    name = "sca_sha3",
    srcs = ["sca_sha3.json"],
)
