// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//==================================================
//==================================================
// This file contains the Excluded objects
// Generated By User: chencindy
// Format Version: 2
// Date: Tue Nov 22 11:14:03 2022
// ExclMode: default
//==================================================
CHECKSUM: "3497701341 3193573764"
INSTANCE: tb.dut.top_earlgrey.u_lc_ctrl
ANNOTATION: "[UNR]: LcCtrlChipGen and LcCtrlChipRev are tied off to design parameters."
Toggle hw_rev_o.chip_gen "logic hw_rev_o.chip_gen[15:0]"
ANNOTATION: "[UNR]: LcCtrlChipGen and LcCtrlChipRev are tied off to design parameters."
Toggle hw_rev_o.chip_rev "logic hw_rev_o.chip_rev[15:0]"
