[package]
name = "earlgrey"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
opentitan_common = { path = "../opentitan_common" }
tock_deps = { path = "../../tock_deps" }
