[package]
name = "earlgrey"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[features]
device_fpga = ["device_specified"]
device_verilator = ["device_specified"]
device_specified = []

[dependencies]
opentitan_common = { path = "../opentitan_common" }
tock_deps = { path = "../../tock_deps" }
dif = { path = "../../dif" }
