# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:autogen.bzl", "otp_image")

package(default_visibility = ["//visibility:public"])

otp_image(
    name = "otp_test_img",
    src = "otp_ctrl_img_rom_testing.hjson",
)
