# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tock"
version = "0.1.0"
authors = ["lowRISC contributors"]
edition = "2018"

[dependencies]
components = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
rv32i = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
capsules = { git = "https://github.com/tock/tock", rev = "d37ef3d2"}
kernel = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }
tock_rt0 = { git = "https://github.com/tock/tock", rev = "d37ef3d2" }