# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary")

package(default_visibility = ["//visibility:public"])

otbn_binary(
    name = "otbn_char_dmem_access",
    srcs = [
        "otbn_char_dmem_access.s",
    ],
)

otbn_binary(
    name = "otbn_char_hardware_dmem_op_loop",
    srcs = [
        "otbn_char_hardware_dmem_op_loop.s",
    ],
)

otbn_binary(
    name = "otbn_char_hardware_reg_op_loop",
    srcs = [
        "otbn_char_hardware_reg_op_loop.s",
    ],
)

otbn_binary(
    name = "otbn_char_jal",
    srcs = [
        "otbn_char_jal.s",
    ],
)

otbn_binary(
    name = "otbn_char_rf",
    srcs = [
        "otbn_char_rf.s",
    ],
)

otbn_binary(
    name = "otbn_char_unrolled_dmem_op_loop",
    srcs = [
        "otbn_char_unrolled_dmem_op_loop.s",
    ],
)

otbn_binary(
    name = "otbn_char_unrolled_reg_op_loop",
    srcs = [
        "otbn_char_unrolled_reg_op_loop.s",
    ],
)

otbn_binary(
    name = "otbn_key_sideload",
    srcs = [
        "otbn_key_sideload.s",
    ],
)

otbn_binary(
    name = "otbn_load_integrity",
    srcs = [
        "otbn_load_integrity.s",
    ],
)
