// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_22_16_enc (
  input        [15:0] data_i,
  output logic [21:0] data_o
);

  always_comb begin : p_encode
    data_o = 22'(data_i);
    data_o[16] = ^(data_o & 22'h005555);
    data_o[17] = ^(data_o & 22'h00AA55);
    data_o[18] = ^(data_o & 22'h0095A9);
    data_o[19] = ^(data_o & 22'h0069A6);
    data_o[20] = ^(data_o & 22'h00669A);
    data_o[21] = ^(data_o & 22'h009A6A);
  end

endmodule : prim_secded_22_16_enc
