// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 8 -k 64 -s 3843802612 -c hsiao

module prim_secded_72_64_enc (
  input        [63:0] in,
  output logic [71:0] out
);

  always_comb begin : p_encode
    out = 72'(in);
    out[64] = ^(out & 72'h009B000000001FFFFF);
    out[65] = ^(out & 72'h007900000FFFE0003F);
    out[66] = ^(out & 72'h00DC003FF003E007C1);
    out[67] = ^(out & 72'h00370FC0F03C207842);
    out[68] = ^(out & 72'h00EA71C711C4438884);
    out[69] = ^(out & 72'h002FB65926488C9108);
    out[70] = ^(out & 72'h00E6DAAA4A91152210);
    out[71] = ^(out & 72'h00D5ED348D221A4420);
  end

endmodule : prim_secded_72_64_enc
