# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "aes_block_schema",
    srcs = ["aes_block_schema.json"],
)

filegroup(
    name = "ecdsa_sig_ver_schema",
    srcs = ["ecdsa_sig_ver_schema.json"],
)

exports_files([
    "aes_kw_schema.json",
    "aes_gcm_schema.json",
    "ecdh_schema.json",
    "hash_schema.json",
    "hmac_schema.json",
    "kmac_schema.json",
])
