// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_CMVP_H_
#define OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_CMVP_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "sw/device/lib/crypto/impl/state.h"
#include "sw/device/lib/crypto/include/cmvp.h"
#include "sw/device/lib/crypto/include/datatypes.h"

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

/**
 * Enum for Cryptolib API functions for CMVP service indicator.
 */
typedef enum otcrypto_cmvp_function {
  // Symmetric ciphers
  OTCRYPTO_FUNCTION_AES,
  OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT,
  OTCRYPTO_FUNCTION_AES_GCM_DECRYPT,
  OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_INIT,
  OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_INIT,
  OTCRYPTO_FUNCTION_AES_GCM_UPDATE_AAD,
  OTCRYPTO_FUNCTION_AES_GCM_UPDATE_ENCRYPTED_DATA,
  OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_FINAL,
  OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_FINAL,

  // MACs
  OTCRYPTO_FUNCTION_CMAC,
  OTCRYPTO_FUNCTION_CMAC_INIT,
  OTCRYPTO_FUNCTION_CMAC_UPDATE,
  OTCRYPTO_FUNCTION_CMAC_FINAL,
  OTCRYPTO_FUNCTION_HMAC,
  OTCRYPTO_FUNCTION_HMAC_INIT,
  OTCRYPTO_FUNCTION_HMAC_UPDATE,
  OTCRYPTO_FUNCTION_HMAC_FINAL,
  OTCRYPTO_FUNCTION_KMAC,
  OTCRYPTO_FUNCTION_KMAC_KDF,

  // Hash / XOF
  OTCRYPTO_FUNCTION_SHA2_256,
  OTCRYPTO_FUNCTION_SHA2_384,
  OTCRYPTO_FUNCTION_SHA2_512,
  OTCRYPTO_FUNCTION_SHA2_INIT,
  OTCRYPTO_FUNCTION_SHA2_UPDATE,
  OTCRYPTO_FUNCTION_SHA2_FINAL,
  OTCRYPTO_FUNCTION_SHA3_224,
  OTCRYPTO_FUNCTION_SHA3_256,
  OTCRYPTO_FUNCTION_SHA3_384,
  OTCRYPTO_FUNCTION_SHA3_512,
  OTCRYPTO_FUNCTION_SHAKE128,
  OTCRYPTO_FUNCTION_SHAKE256,
  OTCRYPTO_FUNCTION_CSHAKE128,
  OTCRYPTO_FUNCTION_CSHAKE256,

  // DRBG
  OTCRYPTO_FUNCTION_DRBG_INSTANTIATE,
  OTCRYPTO_FUNCTION_DRBG_RESEED,
  OTCRYPTO_FUNCTION_DRBG_GENERATE,
  OTCRYPTO_FUNCTION_DRBG_MANUAL_INSTANTIATE,
  OTCRYPTO_FUNCTION_DRBG_MANUAL_RESEED,
  OTCRYPTO_FUNCTION_DRBG_MANUAL_GENERATE,

  // KDF
  OTCRYPTO_FUNCTION_HKDF,
  OTCRYPTO_FUNCTION_HKDF_EXTRACT,
  OTCRYPTO_FUNCTION_HKDF_EXPAND,
  OTCRYPTO_FUNCTION_KDF_CTR_HMAC,

  // Key transport / keyblob
  OTCRYPTO_FUNCTION_SYMMETRIC_KEYGEN,
  OTCRYPTO_FUNCTION_HW_BACKED_KEYGEN,
  OTCRYPTO_FUNCTION_KEY_WRAP,
  OTCRYPTO_FUNCTION_KEY_UNWRAP,

  // RSA
  OTCRYPTO_FUNCTION_RSA_PUBLIC_KEY_CONSTRUCT,
  OTCRYPTO_FUNCTION_RSA_PRIVATE_KEY_FROM_EXPONENTS,
  OTCRYPTO_FUNCTION_RSA_KEYGEN,
  OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR,
  OTCRYPTO_FUNCTION_RSA_SIGN,
  OTCRYPTO_FUNCTION_RSA_VERIFY,
  OTCRYPTO_FUNCTION_RSA_ENCRYPT,
  OTCRYPTO_FUNCTION_RSA_DECRYPT,
  OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_START,
  OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_FINALIZE,

  // ECC P-256
  OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN,
  OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_VERIFY,
  OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY,
  OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN,
  OTCRYPTO_FUNCTION_ECDH_P256,
  OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECC_P256_POINT_ON_CURVE,
  OTCRYPTO_FUNCTION_ECC_P256_BASE_POINT_MULT,

  // ECC P-384
  OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_VERIFY,
  OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY,
  OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN,
  OTCRYPTO_FUNCTION_ECDH_P384,
  OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_START,
  OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ECC_P384_POINT_ON_CURVE,
  OTCRYPTO_FUNCTION_ECC_P384_BASE_POINT_MULT,

  // Curve25519 (Ed25519 / X25519)
  OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE,
  OTCRYPTO_FUNCTION_ED25519_SIGN,
  OTCRYPTO_FUNCTION_ED25519_SIGN_VERIFY,
  OTCRYPTO_FUNCTION_ED25519_VERIFY,
  OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_START,
  OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ED25519_SIGN_PART1_ASYNC_START,
  OTCRYPTO_FUNCTION_ED25519_SIGN_PART2_ASYNC_START,
  OTCRYPTO_FUNCTION_ED25519_SIGN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_START,
  OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_X25519_KEYGEN,
  OTCRYPTO_FUNCTION_X25519,
  OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_START,
  OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_FINALIZE,
  OTCRYPTO_FUNCTION_X25519_ASYNC_START,
  OTCRYPTO_FUNCTION_X25519_ASYNC_FINALIZE,

  // Self-integrity
  OTCRYPTO_FUNCTION_INTEGRITY_CHECK,

  // Last element sentinel
  OTCRYPTO_FUNCTION_MAX,
} otcrypto_cmvp_function_t;

/**
 * Compile-time approved status for Cryptolib API functions.
 * 1 indicates CMVP approved service, 0 indicates non-approved service.
 */
// Symmetric ciphers
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_INIT 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_INIT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_UPDATE_AAD 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_UPDATE_ENCRYPTED_DATA 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_FINAL 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_FINAL 1

// MACs
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_INIT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_UPDATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_FINAL 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_INIT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_UPDATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_FINAL 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KMAC 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KMAC_KDF 1

// Hash / XOF
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_256 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_384 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_512 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_INIT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_UPDATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_FINAL 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_224 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_256 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_384 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_512 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHAKE128 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHAKE256 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CSHAKE128 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CSHAKE256 1

// DRBG
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_INSTANTIATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_RESEED 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_GENERATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_INSTANTIATE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_RESEED 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_GENERATE 0

// KDF
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF_EXTRACT 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF_EXPAND 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KDF_CTR_HMAC 1

// Key transport / keyblob
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SYMMETRIC_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HW_BACKED_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KEY_WRAP 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KEY_UNWRAP 1

// RSA
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_PUBLIC_KEY_CONSTRUCT 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_PRIVATE_KEY_FROM_EXPONENTS 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_FINALIZE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_START \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_FINALIZE \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_FINALIZE 0

// ECC P-256
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_VERIFY 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_FINALIZE \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_START \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_FINALIZE \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K_ASYNC_START \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_START \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_FINALIZE \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_FINALIZE \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P256_POINT_ON_CURVE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P256_BASE_POINT_MULT 1

// ECC P-384
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_VERIFY 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_FINALIZE \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K_ASYNC_START \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_FINALIZE \
  0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P384_POINT_ON_CURVE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P384_BASE_POINT_MULT 1

// Curve25519 (Ed25519 / X25519)
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_VERIFY 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_START \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_FINALIZE \
  1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_PART1_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_PART2_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_ASYNC_FINALIZE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_START 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_FINALIZE 1
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_FINALIZE 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_ASYNC_START 0
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_ASYNC_FINALIZE 0

// Self-integrity
#define OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_INTEGRITY_CHECK 1

#ifdef FIPS_MODE

/**
 * Marks the start of a CMVP-approved service.
 *
 * If this is the outermost call (cmvp_call_depth == 0), the indicator is set
 * to kOtcryptoCmvpApprovedService. Increments cmvp_call_depth.
 */
void otcrypto_cmvp_start_approved(void);

/**
 * Marks the start of a non-approved service.
 *
 * If this is the outermost call (cmvp_call_depth == 0), the indicator is set
 * to kOtcryptoCmvpNotApprovedService. Increments cmvp_call_depth.
 */
void otcrypto_cmvp_start_not_approved(void);

/**
 * Overrides the CMVP service indicator to not approved.
 *
 * Used when parameter validation determines the service is non-compliant
 * (e.g. non-approved key size, short tag, user-supplied DRBG, etc.).
 */
void otcrypto_cmvp_override_not_approved(void);

/**
 * Decrements cmvp_call_depth when a service finishes.
 */
void otcrypto_cmvp_end_service(void);

#define OTCRYPTO_CMVP_DISPATCH_1 otcrypto_cmvp_start_approved()
#define OTCRYPTO_CMVP_DISPATCH_0 otcrypto_cmvp_start_not_approved()
#define OTCRYPTO_CMVP_GLUE(a, b) a##b
#define OTCRYPTO_CMVP_EXPAND_DISPATCH(approved) \
  OTCRYPTO_CMVP_GLUE(OTCRYPTO_CMVP_DISPATCH_, approved)
#define OTCRYPTO_SET_CMVP_INDICATOR(func) \
  OTCRYPTO_CMVP_EXPAND_DISPATCH(OTCRYPTO_IS_APPROVED_##func)

#define OTCRYPTO_CMVP_OVERRIDE_NOT_APPROVED() \
  otcrypto_cmvp_override_not_approved()

#else  // !defined(FIPS_MODE)

static inline void otcrypto_cmvp_start_approved(void) {}
static inline void otcrypto_cmvp_start_not_approved(void) {}
static inline void otcrypto_cmvp_override_not_approved(void) {}
static inline void otcrypto_cmvp_end_service(void) {}

#define OTCRYPTO_SET_CMVP_INDICATOR(func) ((void)(func))
#define OTCRYPTO_CMVP_OVERRIDE_NOT_APPROVED() ((void)0)

#endif  // FIPS_MODE

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  // OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_CMVP_H_
