// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#include "sw/device/lib/crypto/impl/cmvp.h"

#include <cstddef>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "sw/device/lib/crypto/impl/state.h"
#include "sw/device/lib/crypto/impl/status.h"
#include "sw/device/lib/crypto/include/cmvp.h"
#include "sw/device/lib/crypto/include/datatypes.h"

namespace cmvp_unittest {
namespace {

#define EXPECT_OK(status_) EXPECT_EQ(status_.value, OTCRYPTO_OK.value)

#ifdef FIPS_MODE
const bool kCryptoFunctionApproved[OTCRYPTO_FUNCTION_MAX] = {
    [OTCRYPTO_FUNCTION_AES] = (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_DECRYPT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_INIT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_INIT != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_INIT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_INIT != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_UPDATE_AAD] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_UPDATE_AAD != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_UPDATE_ENCRYPTED_DATA] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_UPDATE_ENCRYPTED_DATA !=
         0),
    [OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_FINAL] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_FINAL != 0),
    [OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_FINAL] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_FINAL != 0),
    [OTCRYPTO_FUNCTION_CMAC] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC != 0),
    [OTCRYPTO_FUNCTION_CMAC_INIT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_INIT != 0),
    [OTCRYPTO_FUNCTION_CMAC_UPDATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_UPDATE != 0),
    [OTCRYPTO_FUNCTION_CMAC_FINAL] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CMAC_FINAL != 0),
    [OTCRYPTO_FUNCTION_HMAC] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC != 0),
    [OTCRYPTO_FUNCTION_HMAC_INIT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_INIT != 0),
    [OTCRYPTO_FUNCTION_HMAC_UPDATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_UPDATE != 0),
    [OTCRYPTO_FUNCTION_HMAC_FINAL] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HMAC_FINAL != 0),
    [OTCRYPTO_FUNCTION_KMAC] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KMAC != 0),
    [OTCRYPTO_FUNCTION_KMAC_KDF] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KMAC_KDF != 0),
    [OTCRYPTO_FUNCTION_SHA2_256] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_256 != 0),
    [OTCRYPTO_FUNCTION_SHA2_384] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_384 != 0),
    [OTCRYPTO_FUNCTION_SHA2_512] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_512 != 0),
    [OTCRYPTO_FUNCTION_SHA2_INIT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_INIT != 0),
    [OTCRYPTO_FUNCTION_SHA2_UPDATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_UPDATE != 0),
    [OTCRYPTO_FUNCTION_SHA2_FINAL] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA2_FINAL != 0),
    [OTCRYPTO_FUNCTION_SHA3_224] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_224 != 0),
    [OTCRYPTO_FUNCTION_SHA3_256] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_256 != 0),
    [OTCRYPTO_FUNCTION_SHA3_384] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_384 != 0),
    [OTCRYPTO_FUNCTION_SHA3_512] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHA3_512 != 0),
    [OTCRYPTO_FUNCTION_SHAKE128] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHAKE128 != 0),
    [OTCRYPTO_FUNCTION_SHAKE256] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SHAKE256 != 0),
    [OTCRYPTO_FUNCTION_CSHAKE128] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CSHAKE128 != 0),
    [OTCRYPTO_FUNCTION_CSHAKE256] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_CSHAKE256 != 0),
    [OTCRYPTO_FUNCTION_DRBG_INSTANTIATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_INSTANTIATE != 0),
    [OTCRYPTO_FUNCTION_DRBG_RESEED] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_RESEED != 0),
    [OTCRYPTO_FUNCTION_DRBG_GENERATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_GENERATE != 0),
    [OTCRYPTO_FUNCTION_DRBG_MANUAL_INSTANTIATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_INSTANTIATE != 0),
    [OTCRYPTO_FUNCTION_DRBG_MANUAL_RESEED] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_RESEED != 0),
    [OTCRYPTO_FUNCTION_DRBG_MANUAL_GENERATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_DRBG_MANUAL_GENERATE != 0),
    [OTCRYPTO_FUNCTION_HKDF] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF != 0),
    [OTCRYPTO_FUNCTION_HKDF_EXTRACT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF_EXTRACT != 0),
    [OTCRYPTO_FUNCTION_HKDF_EXPAND] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HKDF_EXPAND != 0),
    [OTCRYPTO_FUNCTION_KDF_CTR_HMAC] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KDF_CTR_HMAC != 0),
    [OTCRYPTO_FUNCTION_SYMMETRIC_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_SYMMETRIC_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_HW_BACKED_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_HW_BACKED_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_KEY_WRAP] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KEY_WRAP != 0),
    [OTCRYPTO_FUNCTION_KEY_UNWRAP] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_KEY_UNWRAP != 0),
    [OTCRYPTO_FUNCTION_RSA_PUBLIC_KEY_CONSTRUCT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_PUBLIC_KEY_CONSTRUCT != 0),
    [OTCRYPTO_FUNCTION_RSA_PRIVATE_KEY_FROM_EXPONENTS] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_PRIVATE_KEY_FROM_EXPONENTS !=
         0),
    [OTCRYPTO_FUNCTION_RSA_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR != 0),
    [OTCRYPTO_FUNCTION_RSA_SIGN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN != 0),
    [OTCRYPTO_FUNCTION_RSA_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY != 0),
    [OTCRYPTO_FUNCTION_RSA_ENCRYPT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT != 0),
    [OTCRYPTO_FUNCTION_RSA_DECRYPT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT != 0),
    [OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYGEN_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_KEYPAIR_FROM_COFACTOR_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_SIGN_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_VERIFY_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_ENCRYPT_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_RSA_DECRYPT_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_ECDH_P256] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256 != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_CONFIG_K_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_SIGN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_DICE_SIGN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P256_VERIFY_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P256_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_ECC_P256_POINT_ON_CURVE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P256_POINT_ON_CURVE != 0),
    [OTCRYPTO_FUNCTION_ECC_P256_BASE_POINT_MULT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P256_BASE_POINT_MULT != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_ECDH_P384] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384 != 0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_CONFIG_K_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_SIGN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDSA_P384_VERIFY_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECDH_P384_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_ECC_P384_POINT_ON_CURVE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P384_POINT_ON_CURVE != 0),
    [OTCRYPTO_FUNCTION_ECC_P384_BASE_POINT_MULT] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ECC_P384_BASE_POINT_MULT != 0),
    [OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_SIGN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN != 0),
    [OTCRYPTO_FUNCTION_ED25519_SIGN_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ED25519_VERIFY] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY != 0),
    [OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_PUBLIC_KEY_FROM_PRIVATE_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_SIGN_PART1_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_PART1_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_SIGN_PART2_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_PART2_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_SIGN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_SIGN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_START !=
         0),
    [OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_ED25519_VERIFY_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_X25519_KEYGEN] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN != 0),
    [OTCRYPTO_FUNCTION_X25519] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519 != 0),
    [OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_KEYGEN_ASYNC_FINALIZE !=
         0),
    [OTCRYPTO_FUNCTION_X25519_ASYNC_START] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_ASYNC_START != 0),
    [OTCRYPTO_FUNCTION_X25519_ASYNC_FINALIZE] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_X25519_ASYNC_FINALIZE != 0),
    [OTCRYPTO_FUNCTION_INTEGRITY_CHECK] =
        (OTCRYPTO_IS_APPROVED_OTCRYPTO_FUNCTION_INTEGRITY_CHECK != 0),
};

static void otcrypto_cmvp_set_indicator(otcrypto_cmvp_function_t function_id) {
  if (kCryptoFunctionApproved[function_id]) {
    otcrypto_cmvp_start_approved();
  } else {
    otcrypto_cmvp_start_not_approved();
  }
}
#else
static void otcrypto_cmvp_set_indicator(otcrypto_cmvp_function_t function_id) {
  (void)function_id;
}
#endif

class CmvpTest : public ::testing::Test {
 protected:
  void SetUp() override {
    // Reset the internal state
    otcrypto_cmvp_service_indicator_t indicator;
    otcrypto_cmvp_service_indicator(&indicator);
  }
};

TEST_F(CmvpTest, NullIndicatorReturnsBadArgs) {
  EXPECT_EQ(otcrypto_cmvp_service_indicator(nullptr).value,
            OTCRYPTO_BAD_ARGS.value);
}

TEST_F(CmvpTest, InitialIndicatorIsNoService) {
  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpApprovedService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNoService);
}

#ifdef FIPS_MODE

TEST_F(CmvpTest, QueryResetsIndicatorToNoService) {
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpApprovedService);

  // Subsequent call should return kOtcryptoCmvpNoService
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNoService);
}

TEST_F(CmvpTest, ApprovedService) {
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpApprovedService);
}

TEST_F(CmvpTest, NotApprovedService) {
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_HKDF);
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNotApprovedService);
}

TEST_F(CmvpTest, OverrideNotApproved) {
  // Start with an approved function
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  // Override to not approved (e.g., due to unapproved key size)
  otcrypto_cmvp_override_not_approved();
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNotApprovedService);
}

TEST_F(CmvpTest, NestedCallPreservesOuterApprovedStatus) {
  // Outer call: approved (e.g. AES)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);

  // Inner call: not approved (e.g. HKDF)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_HKDF);
  otcrypto_cmvp_end_service();

  // Outer call finishes
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpApprovedService);
}

TEST_F(CmvpTest, NestedCallPreservesOuterNotApprovedStatus) {
  // Outer call: not approved (e.g. HKDF)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_HKDF);

  // Inner call: approved (e.g. AES)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  otcrypto_cmvp_end_service();

  // Outer call finishes
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNotApprovedService);
}

TEST_F(CmvpTest, QueryResetsCallDepth) {
  // Suppose an error occurred and end_service was missed (call depth > 0)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  // indicator called resets depth to 0
  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpApprovedService);

  // Next call should be recognized as outermost (depth 0)
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_HKDF);
  otcrypto_cmvp_end_service();
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNotApprovedService);
}

TEST_F(CmvpTest, ApprovedTableCompleteness) {
  for (size_t i = 0; i < OTCRYPTO_FUNCTION_MAX; ++i) {
    otcrypto_cmvp_function_t func = static_cast<otcrypto_cmvp_function_t>(i);
    otcrypto_cmvp_set_indicator(func);
    otcrypto_cmvp_end_service();

    otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpNoService;
    EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));

    if (kCryptoFunctionApproved[i]) {
      EXPECT_EQ(indicator, kOtcryptoCmvpApprovedService)
          << "Function index " << i << " expected approved";
    } else {
      EXPECT_EQ(indicator, kOtcryptoCmvpNotApprovedService)
          << "Function index " << i << " expected not approved";
    }
  }
}

// Verification of key requirements from user specification
TEST_F(CmvpTest, SpecificationKeyRequirements) {
  // AES-GCM Encrypt is not approved (caller provides IV)
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_AES_GCM_ENCRYPT_INIT]);
  // AES-GCM Decrypt is approved
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_AES_GCM_DECRYPT]);
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_AES_GCM_DECRYPT_INIT]);

  // DRBG: generate, instantiate, reseed are approved, manual is not
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_DRBG_GENERATE]);
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_DRBG_INSTANTIATE]);
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_DRBG_RESEED]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_DRBG_MANUAL_GENERATE]);

  // HKDF is not approved
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_HKDF]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_HKDF_EXTRACT]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_HKDF_EXPAND]);

  // ECDH is not approved
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ECDH_P256]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ECDH_P384]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ECDH_P256_KEYGEN]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ECDH_P384_KEYGEN]);

  // Ed25519 is approved
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ED25519_SIGN]);
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ED25519_VERIFY]);
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_ED25519_SIGN_VERIFY]);

  // X25519 is not approved
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_X25519]);
  EXPECT_FALSE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_X25519_KEYGEN]);

  // Self-integrity check is approved
  EXPECT_TRUE(kCryptoFunctionApproved[OTCRYPTO_FUNCTION_INTEGRITY_CHECK]);
}

#else  // !defined(FIPS_MODE)

TEST_F(CmvpTest, NonFipsAlwaysReturnsNoService) {
  otcrypto_cmvp_set_indicator(OTCRYPTO_FUNCTION_AES);
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpApprovedService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNoService);
}

TEST_F(CmvpTest, NonFipsMacrosAreNoOps) {
  OTCRYPTO_SET_CMVP_INDICATOR(OTCRYPTO_FUNCTION_AES);
  OTCRYPTO_CMVP_OVERRIDE_NOT_APPROVED();
  otcrypto_cmvp_end_service();

  otcrypto_cmvp_service_indicator_t indicator = kOtcryptoCmvpApprovedService;
  EXPECT_OK(otcrypto_cmvp_service_indicator(&indicator));
  EXPECT_EQ(indicator, kOtcryptoCmvpNoService);
}

#endif  // FIPS_MODE

}  // namespace
}  // namespace cmvp_unittest
