[package]
name = "tock_deps"
version = "0.1.0"
authors = ["Silvestrs Timofejevs <silvestrst@lowrisc.org>"]
edition = "2018"

[dependencies]
components = { path = "../tock_local/boards/components" }
rv32i = { path = "../tock_local/arch/rv32i" }
capsules = { path = "../tock_local/capsules" }
kernel = { path = "../tock_local/kernel" }
tock_rt0 = { path = "../tock_local/libraries/tock-rt0" }
