// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef OPENTITAN_HW_IP_AES_PRE_DV_AES_TB_CPP_AES_TLUL_SEQUENCE_COMMON_H_
#define OPENTITAN_HW_IP_AES_PRE_DV_AES_TB_CPP_AES_TLUL_SEQUENCE_COMMON_H_

#define AES_KEY_SHARE0_0 0x0
#define AES_KEY_SHARE1_0 0x20
#define AES_IV_0 0x40
#define AES_DATA_IN_0 0x50
#define AES_DATA_OUT_0 0x60
#define AES_CONFIG 0x70
#define AES_TRIGGER 0x74
#define AES_STATUS 0x78

#define AES_CTRL_KEY_LEN_OFFSET 7
#define AES_CTRL_MANUAL_OPERATION_OFFSET 10

#endif  // OPENTITAN_HW_IP_AES_PRE_DV_AES_TB_CPP_AES_TLUL_SEQUENCE_COMMON_H_
