# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "rtl_files",
    srcs = glob(["**"]) + [
        "//hw/top_earlgrey/ip/ast:rtl_files",
        "//hw/top_earlgrey/ip/sensor_ctrl:rtl_files",
        "//hw/top_earlgrey/ip/xbar:rtl_files",
        "//hw/top_earlgrey/ip/xbar_main:rtl_files",
        "//hw/top_earlgrey/ip/xbar_peri:rtl_files",
        "//hw/top_earlgrey/ip_autogen/alert_handler:rtl_files",
        "//hw/top_earlgrey/ip_autogen/clkmgr:rtl_files",
        "//hw/top_earlgrey/ip_autogen/flash_ctrl:rtl_files",
        "//hw/top_earlgrey/ip_autogen/gpio:rtl_files",
        "//hw/top_earlgrey/ip_autogen/otp_ctrl:rtl_files",
        "//hw/top_earlgrey/ip_autogen/pinmux:rtl_files",
        "//hw/top_earlgrey/ip_autogen/pwm:rtl_files",
        "//hw/top_earlgrey/ip_autogen/pwrmgr:rtl_files",
        "//hw/top_earlgrey/ip_autogen/rstmgr:rtl_files",
        "//hw/top_earlgrey/ip_autogen/rv_core_ibex:rtl_files",
        "//hw/top_earlgrey/ip_autogen/rv_plic:rtl_files",
    ],
)
