# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Publish Bazel test results
description: Merge Bazel test results and publish the report

inputs:
  merged-results:
    description: Path to place merged JUnit report.
    default: test_results.xml
  artifact-name:
    description: Name of uploaded artifact. Leave empty to skip upload.
    default: ''
  upload-to-bucket:
    description: Whether to upload results to the Google Cloud Bucket.
    default: "false"
  bucket-job-folder-name:
    description: Google Cloud Bucket folder name for uploaded test results.
    default: "fpga"
  branch:
    description: Branch name.
    default: "${{ github.ref }}"

runs:
  using: composite
  steps:
    # Bazel produce one xml for each test. Merge them together.
    - name: Merge JUnit reports
      shell: bash
      run: |
        if find -L bazel-out -name "test.xml" | grep -F '' >> /tmp/test-xmls; then
          cat /tmp/test-xmls | xargs merge-junit -o "${{ inputs.merged-results }}"
        else
          # No test results to upload
          echo "report_exists=false" >> $GITHUB_ENV
        fi

    - name: Add hostname to testsuites
      if: ${{ report_exists == 'true' }}
      shell: bash
      run: |
        xmlstarlet ed --inplace -i '/testsuites/testsuite' -t attr -n hostname -v "${{ runner.name }}" "${{ inputs.merged-results }}"

    - name: Upload report as artifact
      if: ${{ report_exists == 'true' && inputs.artifact-name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.merged-results }}
        # In case this is from a re-run
        overwrite: true

    - name: Upload report to Google Cloud
      if: ${{ report_exists == 'true' && inputs.upload-to-bucket != 'false' }}
      shell: bash
      run: |
        BUCKET_PATH=opentitan-test-results/job/${{ inputs.bucket-job-folder-name }}/branch/${{ inputs.branch }}/$(date +%Y-%m-%d-%H%M%S)_test_results.xml
        printf "BUCKET_PATH=${BUCKET_PATH}\n" >> $GITHUB_OUTPUT
        gcloud storage cp "${{ inputs.merged-results }}" "gs://${BUCKET_PATH}"

    - name: Publish job summary
      uses: mikepenz/action-junit-report@ec3a351c13e080dc4fa94c49ab7ad5bf778a9668 # v5
      with:
        report_paths: ${{ inputs.merged-results }}
        annotate_only: true
        detailed_summary: true
