constraint_value(
    name = "armv6-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "armv7-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "armv7e-m",
    constraint_setting = "@platforms//cpu:cpu",
    visibility = ["//visibility:public"],
)
